house_price_app/blueprint_routes.py
from house_price_app.utilities import get_years, get_data
from flask import render_template, Blueprint, abort


# Define the Blueprint
main_bp = Blueprint("main", __name__)


@main_bp.route("/api")
def data():
    """Returns the home page"""
    response = get_years()
    return render_template("api_index.html", year=response)


@main_bp.route("/api/display_years/<year>")
def display_event(year):
    '''
    Renders the display with the year and its corresponding data

    Parameters
    ----------
    year: Any
        the year
    Returns
    -------
    render_template: function
        function to render the template using the year and its data
    '''
    data = get_data(year)
    if data:
        return render_template("data_output.html", data=data)
    else:
        abort(404)

house_price_app/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
<dd>{{ field( **kwargs)|safe }}
    {% if field.errors %}
    <ul class=errors>
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</dd>
{% endmacro %}

house_price_app/templates/api_index.html
{% extends 'layout.html' %}
{% set title = 'Past house price data' %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    h1 {text-align: center;
    text-decoration: underline;}
    table, th, td {
      border: 1px solid rgb(0, 0, 0);
      border-collapse: collapse;
      
    }
    
    table.center {
      margin-left: auto; 
      margin-right: auto;
    } 
    ul {
        list-style: none;
        padding-left: 0;
          }
    tr:nth-child(even) {background-color: #f7f7f7;}
    th {
        background-color: #000000;
        color: rgb(255, 255, 255);
        text-align: center
        }
    td {
        text-align: center;
        }
        
    </style>
    </head>
    <body>


<h1 id="title">House price & GDP data from 1952</h1>
<br>
<h4>To find information of house prices from the past, select a year from below:</h4>
<br>
<table class="center">  
    <tr>
      <th style="width:200px">1952-1970</th>
      <th style="width:200px">1980-1998</th>
      <th style="width:200px">2000-2015</th>
    </tr>
    <tr>
      <td style="text-align: center"><ul style="list-style: none;">
        {% for x in range(0,19) %}
        <li><a id="{{ year[x]['Date'] }}" href="{{ url_for('main.display_event', year=year[x]['Date'])}}">
            {{year[x]['Date'] }} </a></li>
        {% endfor %}
    </ul></td >
      <td style="text-align: center"><ul style="list-style: none;">
        {% for x in range(28,47) %}
        <li><a id="{{ year[x]['Date'] }}" href="{{ url_for('main.display_event', year=year[x]['Date'])}}">
            {{year[x]['Date'] }} </a></li>
        {% endfor %}
    </ul></td>
      <td style="text-align: center"><ul style="list-style: none;">
        {% for x in range(48,64) %}
        <li><a id="{{ year[x]['Date'] }}" href="{{ url_for('main.display_event', year=year[x]['Date'])}}">
            {{year[x]['Date'] }} </a></li>
        {% endfor %}
    
    </ul></td>
    </tr>
  </table>

{% endblock %}

house_price_app/templates/data_output.html
{% extends 'layout.html' %}
{% set title = data['Date'] %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    h1 {text-align: center;
        text-decoration: underline;}
    table, th, td {
      border: 1px solid rgb(0, 0, 0);
      border-collapse: collapse;
      
    }
    
    table.center {
      margin-left: auto; 
      margin-right: auto;
    } 
    ul {
        list-style: none;
        padding-left: 0;
          }
    tr:nth-child(even) {background-color: #f7f7f7;}
    th {
        background-color: #000000;
        color: rgb(255, 255, 255);
        text-align: center
        }
    td {
        text-align: center;
        }
        
    </style>
    </head>
    <body>

<br>
<h1>Year: {{ data['Date']}}</h1>
<br>
<br>
<table class="center">  
    <tr>
      <th style="width:200px">Average House</th>
      <th style="width:200px">New Houses</th>
      <th style="width:200px">Modern Houses</th>
      <th style="width:200px">Older Houses</th>
      <th style="width:200px">GDP</th>
    </tr>
    <tr>
      <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (All)">£{{ data['price_all']}}</li>
    </ul></td >
      <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (New)">£{{ data['price_new']}}</li>
    </ul></td>
    <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (Modern)">£{{ data['price_modern']}}</li>
    </ul></td>
    <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (Older)">£{{ data['price_old']}}
    </ul></td>
    <td style="text-align: center"><ul style="list-style: none;">
        <li id="GDP">£{{ data['gdp']}} </li>
    </tr>
  </table>
{% endblock %}

house_price_app/templates/event.html
{% extends 'layout.html' %}
{% set title = event['Date'] %}
{% block content %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    h1 {text-align: center;
        text-decoration: underline;}
    table, th, td {
      border: 1px solid rgb(0, 0, 0);
      border-collapse: collapse;
      
    }
    
    table.center {
      margin-left: auto; 
      margin-right: auto;
    } 
    ul {
        list-style: none;
        padding-left: 0;
          }
    tr:nth-child(even) {background-color: #f7f7f7;}
    th {
        background-color: #4e91dd;
        color: rgb(0, 0, 0);
        text-align: center
        }
    td {
        text-align: center;
        }
        
    </style>
    </head>
    <body>

<br>
<h1>Year: {{ event['Date']}}</h1>
<br>
<br>
<table class="center">  
    <tr>
      <th style="width:200px">Average House</th>
      <th style="width:200px">New Houses</th>
      <th style="width:200px">Modern Houses</th>
      <th style="width:200px">Older Houses</th>
      <th style="width:200px">GDP</th>
    </tr>
    <tr>
      <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (All)">£{{ event['price_all']}}</li>
    </ul></td >
      <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (New)">£{{ event['price_new']}}</li>
    </ul></td>
    <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (Modern)">£{{ event['price_modern']}}</li>
    </ul></td>
    <td style="text-align: center"><ul style="list-style: none;">
        <li id="Price (Older)">£{{ event['price_old']}}
    </ul></td>
    <td style="text-align: center"><ul style="list-style: none;">
        <li id="GDP">£{{ event['gdp']}} </li>
    </tr>
  </table>
{% endblock %}

house_price_app/templates/index.html
{% extends 'layout.html' %}
{% set title = 'UK House Prices' %}
{% block content %}

<form method="POST" class="form">
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.year_wanted.label }}
        {{ form.year_wanted(class="form-control") }}
        {% if form.year_wanted.errors %}
        <ul class="text-warning">
            {% for error in form.year_wanted.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.house_type_selection.label }}
        {{ form.house_type_selection(class="form-control") }}
        {% if form.house_type_selection.errors %}
        <ul class="text-warning">
            {% for error in form.house_type_selection.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <br>
    <input id="btn-predict" type="submit" value="Predict House price" class="btn btn-secondary">
    <br>
</form>
<br>
<p id="prediction-text">{{ prediction_text }}</p>

{% endblock %}

house_price_app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>

<body>
    <!-- Flashed messages see https://flask.palletsprojects.com/en/2.2.x/patterns/flashing/ -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class="alert alert-warning">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}

    {% include 'navbar.html' %}
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}"></script>
</body>

</html>

house_price_app/templates/layout_errors.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>

<body>
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

house_price_app/templates/login.html
{% extends 'layout.html' %}
{% from "_formhelpers.html" import render_field %}
{% block content %}
<form method=post action="{{ url_for('login') }}">
    {{ form.csrf_token }}
    {{ render_field(form.email, class="form-control") }}
    {{ render_field(form.password, class="form-control") }}
    {{ render_field(form.remember, class="form-check-input") }}
    <p><button type="submit" class="btn btn-secondary">Login</button></p>
</form>
{% endblock %}

house_price_app/templates/navbar.html
<!-- Navbar -->
<head>
    <link 
    href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" 
    rel="stylesheet"  type='text/css'>
</head>
<nav class="navbar navbar-expand-lg bg-black navbar-dark">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">UK House Price Predictor</a>

        <!-- Icons -->
        <ul class="navbar-nav d-flex flex-row me-1">
            <li id="Homepage">
                <a class="nav-link text-white" href="/"><i class="fa fa-home"></i> Homepage</a>
            </li>
            <li id="Statistics">
                <a class="nav-link text-white" href="/stats"><i class="fa fa-bar-chart"></i> Statistics</a>
            </li>
            <li id="Data">
                <a class="nav-link text-white" href="/api"><i class="fa fa-database"></i> Data</a>
            </li>
            {% if current_user.is_anonymous %}
            <li id="Register">
                <a class="nav-link text-white" href="/register"><i class="fa fa-user-plus"></i> Register</a>
            </li>
            <li id="Login">
                <a class="nav-link text-white" href="/login"><i class="fa fa-user"></i> Login</a>
            </li>
            {% else %}
            <li id="logout">
                <a class="nav-link text-white" href="{{ url_for('logout') }}"><i class="fa fa-power-off"></i> Logout</a>
            {% endif %}
        </ul>
    </div>

    <!-- Container wrapper -->
</nav>
<!-- Navbar -->

house_price_app/templates/register.html
{% extends 'layout.html' %}
{% set title = 'Register' %}
{% block content %}

<form method="POST" class="form">
    {{ form.csrf_token }}
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email(class="form-control") }}
        {% if form.email.errors %}
        <ul class="text-warning">
            {% for error in form.email.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password(class="form-control") }}
        {% if form.password.errors %}
        <ul class="text-warning">
            {% for error in form.password.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <br>
    <input type="submit" value="Register" class = "btn btn-secondary">
</form>

{% endblock %}

house_price_app/templates/stats.html
{% extends 'layout.html' %}
{% set title = 'Dashboard iframe test...' %}
{% block content %}
<style>
iframe{
    display: block; /* iframes are inline by default */ 
    height: 90vh; /* Set height to 100% of the viewport height */ 
    width: 99vw; /* Set width to 100% of the viewport width */
    border: none; /* Remove default border */
}
</style>
<iframe src="http://localhost:5000/dashboard/"></iframe>

{% endblock %}